/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Link from 'next/link';
import SidebarIcon from './SidebarIcon';

 
const Property1Default = styled("div", {
    shouldForwardProp: prop => !["props"].includes(prop)
  })(({ props }) =>({  
  display: `flex`,  
  flexDirection: `row`,  
  width: `258px`,  
  height: `40px`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `13px`,  
  padding: `0px 32px`,  
  boxSizing: `border-box`,  
  backgroundColor: props.isSelected ? `rgba(97, 179, 255, 0.12)` : "unset",  

  "&:hover": {
    backgroundColor: `rgba(97, 179, 255, 0.05)`,
    cursor: `pointer`,
    transition: `all 0.2s ease-in-out`,

    "& $Text": {
      color: `rgba(0, 0, 0, 0.87)`,
      transition: `all 0.2s ease-in-out`,
    }
  }

}));
  
const Text = styled("div", {
    shouldForwardProp: prop => !["props"].includes(prop)
  })(({ theme, props }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: props.isSelected ? `rgba(25, 118, 210, 1)` : `rgba(0, 0, 0, 0.6)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0.64px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  flexGrow: `1`,  
}));
 
function SidebarRow(props) {
  return (
    <Link href={props.href} >
      <Property1Default props={props} >
        <SidebarIcon  icon={props.icon} isSelected={props.isSelected}/>
        <Text props={props} >
          {props.text}
            </Text>
      </Property1Default>
     </Link>
   );
}

export default SidebarRow;
