/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import { IconButton } from '@mui/material';

 
const PropertyDefault = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 2px 5px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `7px`,  
  display: `flex`,  
  flexDirection: `row`,  
  width: `50px`,  
  height: `50px`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  overflow: `hidden`,  
}));
 
function IconBox(props) {
  return (
    <PropertyDefault >
      <IconButton id="button-open-modal" size="medium" color="primary" onClick={props.action} disabled={props.isDisabled} >
        {props.children}
      </IconButton>
    </PropertyDefault>
   );
}

export default IconBox;
