/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { TextField, InputAdornment } from '@mui/material';
import { styled } from '@mui/material/styles';
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';

 
const Search1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 2px 5px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `7px`,  
  display: `flex`,  
  flexDirection: `row`,  
  width: `343px`,  
  height: `50px`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  gap: `24px`,  
  padding: `0px 36px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
}));
  
const TextFieldStandard = styled(TextField)({  
  width: `220px`,  
});
 
function Search(props) {
  return (
    <Search1 >
      <TextFieldStandard 
        variant="standard"
        size="medium"
        placeholder={props.placeholder}
        InputProps={{startAdornment: <InputAdornment position="start"><SearchOutlinedIcon /></InputAdornment>, disableUnderline: true,}}
        onChange={props.handleSearch}
        value={props.value}
      />
     </Search1>
   );
}

export default Search;
